version: "3.8"

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  # Prometheus - Sistema de monitoreo y base de datos de series temporales
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: wayuu-prometheus
    restart: unless-stopped
    network_mode: "host"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--storage.tsdb.retention.size=10GB"
      - "--storage.tsdb.wal-compression"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  # Grafana - Plataforma de visualización y dashboards
  grafana:
    image: grafana/grafana:10.0.0
    container_name: wayuu-grafana
    restart: unless-stopped
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=wayuu2024
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=3001
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel
      - GF_RENDERING_SERVER_URL=http://localhost:8081/render
      - GF_RENDERING_CALLBACK_URL=http://localhost:3001/
      - GF_LOG_FILTERS=rendering:debug
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

  # Node Exporter - Métricas del sistema host
  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: wayuu-node-exporter
    restart: unless-stopped
    network_mode: "host"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  # Alertmanager - Gestión de alertas (opcional)
  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: wayuu-alertmanager
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
      - "--web.external-url=http://localhost:9093"

  # Grafana Image Renderer - Para exportar dashboards como imágenes
  renderer:
    image: grafana/grafana-image-renderer:3.7.0
    container_name: wayuu-renderer
    restart: unless-stopped
    network_mode: "host"
    environment:
      ENABLE_METRICS: "true"
      RENDERING_MODE: default
      RENDERING_CLUSTERING_MODE: default
      RENDERING_CLUSTERING_MAX_CONCURRENCY: 5
