global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'wayuu-translator-monitor'
    environment: 'development'

# Alertmanager configuration (opcional para desarrollo)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Métricas del traductor Wayuu
  - job_name: 'wayuu-translator-backend'
    static_configs:
      - targets: ['localhost:3002']  # IP local del host
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # Métricas del frontend Next.js (si las habilitamos en el futuro)
  - job_name: 'wayuu-translator-frontend'
    static_configs:
      - targets: ['192.168.1.59:4001']  # IP local del host
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    # Solo intentar si el endpoint existe
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: service
        replacement: 'frontend'

  # Métricas del propio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Métricas de Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Métricas del sistema (node_exporter) - opcional
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    honor_labels: true

# Configuración de almacenamiento
# Nota: Estas configuraciones se pasan como argumentos de línea de comandos
# --storage.tsdb.retention.time=30d
# --storage.tsdb.retention.size=10GB
# --storage.tsdb.wal-compression 